source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib', require: 'sinatra/reloader'
gem 'micro_migrations', github: 'svenfuchs/micro_migrations'
gem 'mysql2'
gem 'activerecord', require: 'active_record'
gem 'rb-readline', '~> 0.4.2'
gem 'enumerize', require: 'enumerize'

group :test do
  gem 'rack-test', require: 'rack/test'
  gem 'minitest'
end

group :development do
  gem 'rake'
  gem 'tux'
end