require 'rake/testtask'
require 'micro_migrations'
require 'sinatra/base'
require 'sinatra/contrib'

Rake::TestTask.new('test') do |t|
  t.libs << "./app/models"
  t.test_files = FileList['test/**/*_test.rb']
end
